### ISSUE TITLE
Pasters 

### ISSUE THREAD

**Issue by 69hr** [olliem5/clientbase#3]
Osiris 🥱🥱🐈

**Comment by olliem5** [comment]
no lmao

**Comment by yagel15637** [comment]
> Osiris 🥱🥱🐈

@69hr 100% original code wdym

**Comment by wawddd** [comment]
sex

**Comment by LittleDraily** [comment]
> Osiris 🥱🥱🐈

Yes osiris u got a problem? This is kami base and we love furry's and pasting

**Comment by wawddd** [comment]
:concernedtater:
